[project]
name = "devops-practice-python"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "asyncio>=4.0.0",
    "fastapi>=0.117.1",
    "sqlalchemy>=2.0.43",
    "uvicorn>=0.36.0",
]
